# Generated by Django 5.1.6 on 2025-05-18 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_usermodel_options_alter_usermodel_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='role',
        ),
    ]
