# Generated by Django 5.1.6 on 2025-05-19 02:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_usermodel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='children',
            field=models.ManyToManyField(blank=True, help_text='Parents can be linked to one or more student users.', limit_choices_to={'role': 'student'}, related_name='parents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('parent', 'Parent')], default='student', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
